######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 27 13:15:50 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += p_paths_precalculation.cpp
